### ISSUE TITLE
uses old format

### ISSUE THREAD

**Issue by carbonaming** [Court-Room-Gaming/Qb-Core-vehicle-shared-lua#1]
this uses the older format that isnt supported anymore in qbcore if you want to have a current format it needs to be similar to this
    {['model'] = 'akuma',         ['name'] = 'Akuma',                         ['brand'] = 'Dinka',           ['price'] = 55000,   ['categoryLabel'] = 'Motorcycles',     ['shop'] = 'pdm'},
not this 
['tltypes'] = {
	['name'] = 'Acura TL Type-S',
	['brand'] = 'aston',
	['model'] = 'tltypes',
	['price'] = 24000,
	['category'] = 'aston',
	['categoryLabel'] = 'aston',
	['hash'] = `tltypes`,
	['shop'] = 'luxury',
},

**Comment by Court-Room-Gaming** [comment]
This will be updated with in the next week

**Comment by Court-Room-Gaming** [comment]
i am sorry for the delay as life happens but this has been updated
